/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: string;
  title?: string;
  description?: string;
  tags?: Array<string>;
  type?: 'mobile' | 'web';
  stage?: 'release' | 'dev' | 'unsupported';
  href?: string;
  img?: string;
  color?: string;
  stats?: {
    users?: number;
    rating?: number;
  };
};

export type Event = {
  _id: string;
  _type: 'event';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: string;
  title?: string;
  link?: string;
  description?: string;
  date?: string;
  location?: string;
  attendees?: number;
  type?: 'codingWorkshop' | 'designWorkshop' | 'panel';
  featured?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | Project
  | Event
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: sanity/lib/queries/event.ts
// Variable: EVENTS_QUERY
// Query: *[_type == "event" && date >= now()] | order(date asc) {    _id,    id,    title,    description,    date,    location,    attendees,    type,    featured  }
export type EVENTS_QUERYResult = Array<never>;

// Source: sanity/lib/queries/project.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"]    | order(        select(          stage == "dev" => 0,          stage == "release" => 1,          stage == "unsupported" => 2,          3        ) asc,        _createdAt desc      ) {    _id,    id,    title,    description,    tags,    type,    stage,    href,    img,    color,    stats {      users,      rating    }  }
export type PROJECTS_QUERYResult = Array<{
  _id: string;
  id: string | null;
  title: string | null;
  description: string | null;
  tags: Array<string> | null;
  type: 'mobile' | 'web' | null;
  stage: 'dev' | 'release' | 'unsupported' | null;
  href: string | null;
  img: string | null;
  color: string | null;
  stats: {
    users: number | null;
    rating: number | null;
  } | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "event" && date >= now()] | order(date asc) {\n    _id,\n    id,\n    title,\n    description,\n    date,\n    location,\n    attendees,\n    type,\n    featured\n  }\n': EVENTS_QUERYResult;
    '\n  *[_type == "project"]\n    | order(\n        select(\n          stage == "dev" => 0,\n          stage == "release" => 1,\n          stage == "unsupported" => 2,\n          3\n        ) asc,\n        _createdAt desc\n      ) {\n    _id,\n    id,\n    title,\n    description,\n    tags,\n    type,\n    stage,\n    href,\n    img,\n    color,\n    stats {\n      users,\n      rating\n    }\n  }\n': PROJECTS_QUERYResult;
  }
}
