/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: string;
  title?: string;
  description?: string;
  tags?: Array<string>;
  type?: 'mobile' | 'web';
  stage?: 'release' | 'dev' | 'unsupported';
  href?: string;
  img?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  color?: string;
  stats?: {
    users?: number;
    rating?: number;
  };
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Officer = {
  _id: string;
  _type: 'officer';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: string;
  slug?: Slug;
  givenName?: string;
  familyName?: string;
  current?: boolean;
  specialization?: string;
  positions?: Array<{
    position?: string;
    startYear?: number;
    endYear?: number;
    _type: 'officerPosition';
    _key: string;
  }>;
  logo?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  projects?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'project';
  }>;
  modelFile?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
    };
    media?: unknown;
    _type: 'file';
  };
  bioShort?: string;
  bioLong?: string;
  detailsTitle?: string;
  leadershipStyle?: string;
  nationalities?: Array<
    | 'Afghanistan'
    | '\xC5land Islands'
    | 'Albania'
    | 'Algeria'
    | 'American Samoa'
    | 'Andorra'
    | 'Angola'
    | 'Anguilla'
    | 'Antarctica'
    | 'Antigua & Barbuda'
    | 'Argentina'
    | 'Armenia'
    | 'Aruba'
    | 'Ascension Island'
    | 'Australia'
    | 'Austria'
    | 'Azerbaijan'
    | 'Bahamas'
    | 'Bahrain'
    | 'Bangladesh'
    | 'Barbados'
    | 'Belarus'
    | 'Belgium'
    | 'Belize'
    | 'Benin'
    | 'Bermuda'
    | 'Bhutan'
    | 'Bolivia'
    | 'Bosnia & Herzegovina'
    | 'Botswana'
    | 'Bouvet Island'
    | 'Brazil'
    | 'British Indian Ocean Territory'
    | 'British Virgin Islands'
    | 'Brunei'
    | 'Bulgaria'
    | 'Burkina Faso'
    | 'Burundi'
    | 'Cambodia'
    | 'Cameroon'
    | 'Canada'
    | 'Canary Islands'
    | 'Cape Verde'
    | 'Caribbean Netherlands'
    | 'Cayman Islands'
    | 'Central African Republic'
    | 'Ceuta & Melilla'
    | 'Chad'
    | 'Chile'
    | 'China'
    | 'Christmas Island'
    | 'Clipperton Island'
    | 'Cocos (Keeling) Islands'
    | 'Colombia'
    | 'Comoros'
    | 'Congo - Brazzaville'
    | 'Congo - Kinshasa'
    | 'Cook Islands'
    | 'Costa Rica'
    | 'C\xF4te d\u2019Ivoire'
    | 'Croatia'
    | 'Cuba'
    | 'Cura\xE7ao'
    | 'Cyprus'
    | 'Czechia'
    | 'Denmark'
    | 'Diego Garcia'
    | 'Djibouti'
    | 'Dominica'
    | 'Dominican Republic'
    | 'Ecuador'
    | 'Egypt'
    | 'El Salvador'
    | 'Equatorial Guinea'
    | 'Eritrea'
    | 'Estonia'
    | 'Eswatini'
    | 'Ethiopia'
    | 'European Union'
    | 'Eurozone'
    | 'Falkland Islands'
    | 'Faroe Islands'
    | 'Fiji'
    | 'Finland'
    | 'France'
    | 'French Guiana'
    | 'French Polynesia'
    | 'French Southern Territories'
    | 'Gabon'
    | 'Gambia'
    | 'Georgia'
    | 'Germany'
    | 'Ghana'
    | 'Gibraltar'
    | 'Greece'
    | 'Greenland'
    | 'Grenada'
    | 'Guadeloupe'
    | 'Guam'
    | 'Guatemala'
    | 'Guernsey'
    | 'Guinea'
    | 'Guinea-Bissau'
    | 'Guyana'
    | 'Haiti'
    | 'Heard & McDonald Islands'
    | 'Honduras'
    | 'Hong Kong SAR China'
    | 'Hungary'
    | 'Iceland'
    | 'India'
    | 'Indonesia'
    | 'Iran'
    | 'Iraq'
    | 'Ireland'
    | 'Isle of Man'
    | 'Israel'
    | 'Italy'
    | 'Jamaica'
    | 'Japan'
    | 'Jersey'
    | 'Jordan'
    | 'Kazakhstan'
    | 'Kenya'
    | 'Kiribati'
    | 'Kosovo'
    | 'Kuwait'
    | 'Kyrgyzstan'
    | 'Laos'
    | 'Latvia'
    | 'Lebanon'
    | 'Lesotho'
    | 'Liberia'
    | 'Libya'
    | 'Liechtenstein'
    | 'Lithuania'
    | 'Luxembourg'
    | 'Macao SAR China'
    | 'Madagascar'
    | 'Malawi'
    | 'Malaysia'
    | 'Maldives'
    | 'Mali'
    | 'Malta'
    | 'Marshall Islands'
    | 'Martinique'
    | 'Mauritania'
    | 'Mauritius'
    | 'Mayotte'
    | 'Mexico'
    | 'Micronesia'
    | 'Moldova'
    | 'Monaco'
    | 'Mongolia'
    | 'Montenegro'
    | 'Montserrat'
    | 'Morocco'
    | 'Mozambique'
    | 'Myanmar (Burma)'
    | 'Namibia'
    | 'Nauru'
    | 'Nepal'
    | 'Netherlands'
    | 'New Caledonia'
    | 'New Zealand'
    | 'Nicaragua'
    | 'Niger'
    | 'Nigeria'
    | 'Niue'
    | 'Norfolk Island'
    | 'North Korea'
    | 'North Macedonia'
    | 'Northern Mariana Islands'
    | 'Norway'
    | 'Oman'
    | 'Pakistan'
    | 'Palau'
    | 'Palestine'
    | 'Panama'
    | 'Papua New Guinea'
    | 'Paraguay'
    | 'Peru'
    | 'Philippines'
    | 'Pitcairn Islands'
    | 'Poland'
    | 'Portugal'
    | 'Puerto Rico'
    | 'Qatar'
    | 'R\xE9union'
    | 'Romania'
    | 'Russia'
    | 'Rwanda'
    | 'Samoa'
    | 'San Marino'
    | 'S\xE3o Tom\xE9 & Pr\xEDncipe'
    | 'Sark'
    | 'Saudi Arabia'
    | 'Senegal'
    | 'Serbia'
    | 'Seychelles'
    | 'Sierra Leone'
    | 'Singapore'
    | 'Sint Maarten'
    | 'Slovakia'
    | 'Slovenia'
    | 'Solomon Islands'
    | 'Somalia'
    | 'South Africa'
    | 'South Georgia & South Sandwich Islands'
    | 'South Korea'
    | 'South Sudan'
    | 'Spain'
    | 'Sri Lanka'
    | 'St. Barth\xE9lemy'
    | 'St. Helena'
    | 'St. Kitts & Nevis'
    | 'St. Lucia'
    | 'St. Martin'
    | 'St. Pierre & Miquelon'
    | 'St. Vincent & Grenadines'
    | 'Sudan'
    | 'Suriname'
    | 'Svalbard & Jan Mayen'
    | 'Sweden'
    | 'Switzerland'
    | 'Syria'
    | 'Taiwan'
    | 'Tajikistan'
    | 'Tanzania'
    | 'Thailand'
    | 'Timor-Leste'
    | 'Togo'
    | 'Tokelau'
    | 'Tonga'
    | 'Trinidad & Tobago'
    | 'Tristan da Cunha'
    | 'Tunisia'
    | 'T\xFCrkiye'
    | 'Turkmenistan'
    | 'Turks & Caicos Islands'
    | 'Tuvalu'
    | 'U.S. Outlying Islands'
    | 'U.S. Virgin Islands'
    | 'Uganda'
    | 'Ukraine'
    | 'United Arab Emirates'
    | 'United Kingdom'
    | 'Uruguay'
    | 'USA'
    | 'Uzbekistan'
    | 'Vanuatu'
    | 'Vatican City'
    | 'Venezuela'
    | 'Vietnam'
    | 'Wallis & Futuna'
    | 'Western Sahara'
    | 'Yemen'
    | 'Zambia'
    | 'Zimbabwe'
  >;
  college?:
    | 'CSOM'
    | 'CBS'
    | 'CDES'
    | 'CEHD'
    | 'CFANS'
    | 'CLA'
    | 'CSE'
    | 'SON'
    | 'CCAPS'
    | 'SOD'
    | 'MED'
    | 'COP'
    | 'HSPA'
    | 'SPH'
    | 'CVM';
  major?: string;
  classYear?: number;
  techStack?: Array<
    | 'adobe suite'
    | 'airflow'
    | 'airtable'
    | 'angular'
    | 'ansible'
    | 'anthropic'
    | 'astro'
    | 'aws'
    | 'babel'
    | 'bootstrap'
    | 'bun'
    | 'c'
    | 'c#'
    | 'c++'
    | 'canva'
    | 'clojure'
    | 'cloudflare'
    | 'confluence'
    | 'dart'
    | 'databricks'
    | 'digitalocean'
    | 'django'
    | 'docker'
    | 'elasticsearch'
    | 'electron'
    | 'elixir'
    | 'erlang'
    | 'excel'
    | 'expo'
    | 'express'
    | 'express.js'
    | 'fastapi'
    | 'figma'
    | 'firebase'
    | 'flask'
    | 'flutter'
    | 'framer'
    | 'gatsby'
    | 'gcp'
    | 'git'
    | 'github'
    | 'gitlab'
    | 'go'
    | 'graphql'
    | 'hadoop'
    | 'haskell'
    | 'hasura'
    | 'hugging face'
    | 'java'
    | 'javascript'
    | 'jenkins'
    | 'jest'
    | 'jira'
    | 'jquery'
    | 'jupyter'
    | 'kafka'
    | 'kotlin'
    | 'kubernetes'
    | 'langchain'
    | 'laravel'
    | 'linear'
    | 'linux'
    | 'mariadb'
    | 'material ui'
    | 'mongodb'
    | 'mui'
    | 'mysql'
    | 'neovim'
    | 'nestjs'
    | 'netlify'
    | 'next.js'
    | 'nextjs'
    | 'nginx'
    | 'node.js'
    | 'nodejs'
    | 'notion'
    | 'numpy'
    | 'nuxt'
    | 'nuxt.js'
    | 'nuxtjs'
    | 'openai'
    | 'openjdk'
    | 'oracle'
    | 'pandas'
    | 'perplexity'
    | 'php'
    | 'postgresql'
    | 'postman'
    | 'prisma'
    | 'python'
    | 'pytorch'
    | 'r'
    | 'rabbitmq'
    | 'react'
    | 'react router'
    | 'react.js'
    | 'reactjs'
    | 'redis'
    | 'redux'
    | 'remix'
    | 'rstudio'
    | 'ruby'
    | 'ruby on rails'
    | 'rust'
    | 'sass'
    | 'scala'
    | 'shopify'
    | 'sklearn'
    | 'slack'
    | 'snowflake'
    | 'socket.io'
    | 'spark'
    | 'springboot'
    | 'sql'
    | 'sqlite'
    | 'storybook'
    | 'supabase'
    | 'svelte'
    | 'swift'
    | 'tableau'
    | 'tailwind'
    | 'tailwind css'
    | 'tailwindcss'
    | 'tensorflow'
    | 'terraform'
    | 'three.js'
    | 'trello'
    | 'typescript'
    | 'ubuntu'
    | 'unity'
    | 'unreal engine'
    | 'vercel'
    | 'vim'
    | 'vite'
    | 'vitest'
    | 'vue'
    | 'vue.js'
    | 'vuejs'
    | 'webflow'
    | 'webpack'
    | 'wordpress'
    | 'xcode'
  >;
  companies?: Array<string>;
  highlights?: Array<string>;
  hobbies?: Array<string>;
  links?: Array<{
    type?:
      | 'portfolio'
      | 'github'
      | 'linkedin'
      | 'x'
      | 'instagram'
      | 'youtube'
      | 'facebook'
      | 'twitch'
      | 'other';
    label?: string;
    url?: string;
    _type: 'officerLink';
    _key: string;
  }>;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Event = {
  _id: string;
  _type: 'event';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: string;
  title?: string;
  link?: string;
  description?: string;
  date?: string;
  location?: string;
  attendees?: number;
  type?: 'codingWorkshop' | 'designWorkshop' | 'panel';
  featured?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Officer
  | Slug
  | Event
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: sanity/lib/queries/event.ts
// Variable: EVENTS_QUERY
// Query: *[_type == "event" && date >= now()] | order(date asc) {    _id,    id,    title,    description,    link,    date,    location,    attendees,    type,    featured  }
export type EVENTS_QUERYResult = Array<never>;

// Source: sanity/lib/queries/officer.ts
// Variable: OFFICERS_QUERY
// Query: *[_type == "officer"] | order(id asc) {      _id,  id,  "slug": slug.current,  givenName,  familyName,  current,  specialization,  positions[] {    position,    startYear,    endYear  },  "logo": logo.asset->url,  "projects": projects[]->{    "identifier": coalesce(slug.current, id)  }[].identifier,  "modelUrl": modelFile.asset->url,  bioShort,  bioLong,  detailsTitle,  leadershipStyle,  nationalities,  college,  major,  classYear,  techStack,  companies,  highlights,  hobbies,  links[] {    type,    label,    url  }  }
export type OFFICERS_QUERYResult = Array<{
  _id: string;
  id: string | null;
  slug: string | null;
  givenName: string | null;
  familyName: string | null;
  current: boolean | null;
  specialization: string | null;
  positions: Array<{
    position: string | null;
    startYear: number | null;
    endYear: number | null;
  }> | null;
  logo: string | null;
  projects: Array<null> | null;
  modelUrl: string | null;
  bioShort: string | null;
  bioLong: string | null;
  detailsTitle: string | null;
  leadershipStyle: string | null;
  nationalities: Array<
    | 'Afghanistan'
    | '\xC5land Islands'
    | 'Albania'
    | 'Algeria'
    | 'American Samoa'
    | 'Andorra'
    | 'Angola'
    | 'Anguilla'
    | 'Antarctica'
    | 'Antigua & Barbuda'
    | 'Argentina'
    | 'Armenia'
    | 'Aruba'
    | 'Ascension Island'
    | 'Australia'
    | 'Austria'
    | 'Azerbaijan'
    | 'Bahamas'
    | 'Bahrain'
    | 'Bangladesh'
    | 'Barbados'
    | 'Belarus'
    | 'Belgium'
    | 'Belize'
    | 'Benin'
    | 'Bermuda'
    | 'Bhutan'
    | 'Bolivia'
    | 'Bosnia & Herzegovina'
    | 'Botswana'
    | 'Bouvet Island'
    | 'Brazil'
    | 'British Indian Ocean Territory'
    | 'British Virgin Islands'
    | 'Brunei'
    | 'Bulgaria'
    | 'Burkina Faso'
    | 'Burundi'
    | 'Cambodia'
    | 'Cameroon'
    | 'Canada'
    | 'Canary Islands'
    | 'Cape Verde'
    | 'Caribbean Netherlands'
    | 'Cayman Islands'
    | 'Central African Republic'
    | 'Ceuta & Melilla'
    | 'Chad'
    | 'Chile'
    | 'China'
    | 'Christmas Island'
    | 'Clipperton Island'
    | 'Cocos (Keeling) Islands'
    | 'Colombia'
    | 'Comoros'
    | 'Congo - Brazzaville'
    | 'Congo - Kinshasa'
    | 'Cook Islands'
    | 'Costa Rica'
    | 'C\xF4te d\u2019Ivoire'
    | 'Croatia'
    | 'Cuba'
    | 'Cura\xE7ao'
    | 'Cyprus'
    | 'Czechia'
    | 'Denmark'
    | 'Diego Garcia'
    | 'Djibouti'
    | 'Dominica'
    | 'Dominican Republic'
    | 'Ecuador'
    | 'Egypt'
    | 'El Salvador'
    | 'Equatorial Guinea'
    | 'Eritrea'
    | 'Estonia'
    | 'Eswatini'
    | 'Ethiopia'
    | 'European Union'
    | 'Eurozone'
    | 'Falkland Islands'
    | 'Faroe Islands'
    | 'Fiji'
    | 'Finland'
    | 'France'
    | 'French Guiana'
    | 'French Polynesia'
    | 'French Southern Territories'
    | 'Gabon'
    | 'Gambia'
    | 'Georgia'
    | 'Germany'
    | 'Ghana'
    | 'Gibraltar'
    | 'Greece'
    | 'Greenland'
    | 'Grenada'
    | 'Guadeloupe'
    | 'Guam'
    | 'Guatemala'
    | 'Guernsey'
    | 'Guinea-Bissau'
    | 'Guinea'
    | 'Guyana'
    | 'Haiti'
    | 'Heard & McDonald Islands'
    | 'Honduras'
    | 'Hong Kong SAR China'
    | 'Hungary'
    | 'Iceland'
    | 'India'
    | 'Indonesia'
    | 'Iran'
    | 'Iraq'
    | 'Ireland'
    | 'Isle of Man'
    | 'Israel'
    | 'Italy'
    | 'Jamaica'
    | 'Japan'
    | 'Jersey'
    | 'Jordan'
    | 'Kazakhstan'
    | 'Kenya'
    | 'Kiribati'
    | 'Kosovo'
    | 'Kuwait'
    | 'Kyrgyzstan'
    | 'Laos'
    | 'Latvia'
    | 'Lebanon'
    | 'Lesotho'
    | 'Liberia'
    | 'Libya'
    | 'Liechtenstein'
    | 'Lithuania'
    | 'Luxembourg'
    | 'Macao SAR China'
    | 'Madagascar'
    | 'Malawi'
    | 'Malaysia'
    | 'Maldives'
    | 'Mali'
    | 'Malta'
    | 'Marshall Islands'
    | 'Martinique'
    | 'Mauritania'
    | 'Mauritius'
    | 'Mayotte'
    | 'Mexico'
    | 'Micronesia'
    | 'Moldova'
    | 'Monaco'
    | 'Mongolia'
    | 'Montenegro'
    | 'Montserrat'
    | 'Morocco'
    | 'Mozambique'
    | 'Myanmar (Burma)'
    | 'Namibia'
    | 'Nauru'
    | 'Nepal'
    | 'Netherlands'
    | 'New Caledonia'
    | 'New Zealand'
    | 'Nicaragua'
    | 'Niger'
    | 'Nigeria'
    | 'Niue'
    | 'Norfolk Island'
    | 'North Korea'
    | 'North Macedonia'
    | 'Northern Mariana Islands'
    | 'Norway'
    | 'Oman'
    | 'Pakistan'
    | 'Palau'
    | 'Palestine'
    | 'Panama'
    | 'Papua New Guinea'
    | 'Paraguay'
    | 'Peru'
    | 'Philippines'
    | 'Pitcairn Islands'
    | 'Poland'
    | 'Portugal'
    | 'Puerto Rico'
    | 'Qatar'
    | 'R\xE9union'
    | 'Romania'
    | 'Russia'
    | 'Rwanda'
    | 'Samoa'
    | 'San Marino'
    | 'S\xE3o Tom\xE9 & Pr\xEDncipe'
    | 'Sark'
    | 'Saudi Arabia'
    | 'Senegal'
    | 'Serbia'
    | 'Seychelles'
    | 'Sierra Leone'
    | 'Singapore'
    | 'Sint Maarten'
    | 'Slovakia'
    | 'Slovenia'
    | 'Solomon Islands'
    | 'Somalia'
    | 'South Africa'
    | 'South Georgia & South Sandwich Islands'
    | 'South Korea'
    | 'South Sudan'
    | 'Spain'
    | 'Sri Lanka'
    | 'St. Barth\xE9lemy'
    | 'St. Helena'
    | 'St. Kitts & Nevis'
    | 'St. Lucia'
    | 'St. Martin'
    | 'St. Pierre & Miquelon'
    | 'St. Vincent & Grenadines'
    | 'Sudan'
    | 'Suriname'
    | 'Svalbard & Jan Mayen'
    | 'Sweden'
    | 'Switzerland'
    | 'Syria'
    | 'Taiwan'
    | 'Tajikistan'
    | 'Tanzania'
    | 'Thailand'
    | 'Timor-Leste'
    | 'Togo'
    | 'Tokelau'
    | 'Tonga'
    | 'Trinidad & Tobago'
    | 'Tristan da Cunha'
    | 'Tunisia'
    | 'T\xFCrkiye'
    | 'Turkmenistan'
    | 'Turks & Caicos Islands'
    | 'Tuvalu'
    | 'U.S. Outlying Islands'
    | 'U.S. Virgin Islands'
    | 'Uganda'
    | 'Ukraine'
    | 'United Arab Emirates'
    | 'United Kingdom'
    | 'Uruguay'
    | 'USA'
    | 'Uzbekistan'
    | 'Vanuatu'
    | 'Vatican City'
    | 'Venezuela'
    | 'Vietnam'
    | 'Wallis & Futuna'
    | 'Western Sahara'
    | 'Yemen'
    | 'Zambia'
    | 'Zimbabwe'
  > | null;
  college:
    | 'CBS'
    | 'CCAPS'
    | 'CDES'
    | 'CEHD'
    | 'CFANS'
    | 'CLA'
    | 'COP'
    | 'CSE'
    | 'CSOM'
    | 'CVM'
    | 'HSPA'
    | 'MED'
    | 'SOD'
    | 'SON'
    | 'SPH'
    | null;
  major: string | null;
  classYear: number | null;
  techStack: Array<
    | 'adobe suite'
    | 'airflow'
    | 'airtable'
    | 'angular'
    | 'ansible'
    | 'anthropic'
    | 'astro'
    | 'aws'
    | 'babel'
    | 'bootstrap'
    | 'bun'
    | 'c'
    | 'c#'
    | 'c++'
    | 'canva'
    | 'clojure'
    | 'cloudflare'
    | 'confluence'
    | 'dart'
    | 'databricks'
    | 'digitalocean'
    | 'django'
    | 'docker'
    | 'elasticsearch'
    | 'electron'
    | 'elixir'
    | 'erlang'
    | 'excel'
    | 'expo'
    | 'express.js'
    | 'express'
    | 'fastapi'
    | 'figma'
    | 'firebase'
    | 'flask'
    | 'flutter'
    | 'framer'
    | 'gatsby'
    | 'gcp'
    | 'git'
    | 'github'
    | 'gitlab'
    | 'go'
    | 'graphql'
    | 'hadoop'
    | 'haskell'
    | 'hasura'
    | 'hugging face'
    | 'java'
    | 'javascript'
    | 'jenkins'
    | 'jest'
    | 'jira'
    | 'jquery'
    | 'jupyter'
    | 'kafka'
    | 'kotlin'
    | 'kubernetes'
    | 'langchain'
    | 'laravel'
    | 'linear'
    | 'linux'
    | 'mariadb'
    | 'material ui'
    | 'mongodb'
    | 'mui'
    | 'mysql'
    | 'neovim'
    | 'nestjs'
    | 'netlify'
    | 'next.js'
    | 'nextjs'
    | 'nginx'
    | 'node.js'
    | 'nodejs'
    | 'notion'
    | 'numpy'
    | 'nuxt.js'
    | 'nuxt'
    | 'nuxtjs'
    | 'openai'
    | 'openjdk'
    | 'oracle'
    | 'pandas'
    | 'perplexity'
    | 'php'
    | 'postgresql'
    | 'postman'
    | 'prisma'
    | 'python'
    | 'pytorch'
    | 'r'
    | 'rabbitmq'
    | 'react router'
    | 'react.js'
    | 'react'
    | 'reactjs'
    | 'redis'
    | 'redux'
    | 'remix'
    | 'rstudio'
    | 'ruby on rails'
    | 'ruby'
    | 'rust'
    | 'sass'
    | 'scala'
    | 'shopify'
    | 'sklearn'
    | 'slack'
    | 'snowflake'
    | 'socket.io'
    | 'spark'
    | 'springboot'
    | 'sql'
    | 'sqlite'
    | 'storybook'
    | 'supabase'
    | 'svelte'
    | 'swift'
    | 'tableau'
    | 'tailwind css'
    | 'tailwind'
    | 'tailwindcss'
    | 'tensorflow'
    | 'terraform'
    | 'three.js'
    | 'trello'
    | 'typescript'
    | 'ubuntu'
    | 'unity'
    | 'unreal engine'
    | 'vercel'
    | 'vim'
    | 'vite'
    | 'vitest'
    | 'vue.js'
    | 'vue'
    | 'vuejs'
    | 'webflow'
    | 'webpack'
    | 'wordpress'
    | 'xcode'
  > | null;
  companies: Array<string> | null;
  highlights: Array<string> | null;
  hobbies: Array<string> | null;
  links: Array<{
    type:
      | 'facebook'
      | 'github'
      | 'instagram'
      | 'linkedin'
      | 'other'
      | 'portfolio'
      | 'twitch'
      | 'x'
      | 'youtube'
      | null;
    label: string | null;
    url: string | null;
  }> | null;
}>;
// Variable: OFFICER_BY_IDENTIFIER_QUERY
// Query: *[    _type == "officer" &&    (      lower(slug.current) == $slugIdentifier ||      lower(id) == $hexIdentifier    )  ][0] {      _id,  id,  "slug": slug.current,  givenName,  familyName,  current,  specialization,  positions[] {    position,    startYear,    endYear  },  "logo": logo.asset->url,  "projects": projects[]->{    "identifier": coalesce(slug.current, id)  }[].identifier,  "modelUrl": modelFile.asset->url,  bioShort,  bioLong,  detailsTitle,  leadershipStyle,  nationalities,  college,  major,  classYear,  techStack,  companies,  highlights,  hobbies,  links[] {    type,    label,    url  }  }
export type OFFICER_BY_IDENTIFIER_QUERYResult = {
  _id: string;
  id: string | null;
  slug: string | null;
  givenName: string | null;
  familyName: string | null;
  current: boolean | null;
  specialization: string | null;
  positions: Array<{
    position: string | null;
    startYear: number | null;
    endYear: number | null;
  }> | null;
  logo: string | null;
  projects: Array<null> | null;
  modelUrl: string | null;
  bioShort: string | null;
  bioLong: string | null;
  detailsTitle: string | null;
  leadershipStyle: string | null;
  nationalities: Array<
    | 'Afghanistan'
    | '\xC5land Islands'
    | 'Albania'
    | 'Algeria'
    | 'American Samoa'
    | 'Andorra'
    | 'Angola'
    | 'Anguilla'
    | 'Antarctica'
    | 'Antigua & Barbuda'
    | 'Argentina'
    | 'Armenia'
    | 'Aruba'
    | 'Ascension Island'
    | 'Australia'
    | 'Austria'
    | 'Azerbaijan'
    | 'Bahamas'
    | 'Bahrain'
    | 'Bangladesh'
    | 'Barbados'
    | 'Belarus'
    | 'Belgium'
    | 'Belize'
    | 'Benin'
    | 'Bermuda'
    | 'Bhutan'
    | 'Bolivia'
    | 'Bosnia & Herzegovina'
    | 'Botswana'
    | 'Bouvet Island'
    | 'Brazil'
    | 'British Indian Ocean Territory'
    | 'British Virgin Islands'
    | 'Brunei'
    | 'Bulgaria'
    | 'Burkina Faso'
    | 'Burundi'
    | 'Cambodia'
    | 'Cameroon'
    | 'Canada'
    | 'Canary Islands'
    | 'Cape Verde'
    | 'Caribbean Netherlands'
    | 'Cayman Islands'
    | 'Central African Republic'
    | 'Ceuta & Melilla'
    | 'Chad'
    | 'Chile'
    | 'China'
    | 'Christmas Island'
    | 'Clipperton Island'
    | 'Cocos (Keeling) Islands'
    | 'Colombia'
    | 'Comoros'
    | 'Congo - Brazzaville'
    | 'Congo - Kinshasa'
    | 'Cook Islands'
    | 'Costa Rica'
    | 'C\xF4te d\u2019Ivoire'
    | 'Croatia'
    | 'Cuba'
    | 'Cura\xE7ao'
    | 'Cyprus'
    | 'Czechia'
    | 'Denmark'
    | 'Diego Garcia'
    | 'Djibouti'
    | 'Dominica'
    | 'Dominican Republic'
    | 'Ecuador'
    | 'Egypt'
    | 'El Salvador'
    | 'Equatorial Guinea'
    | 'Eritrea'
    | 'Estonia'
    | 'Eswatini'
    | 'Ethiopia'
    | 'European Union'
    | 'Eurozone'
    | 'Falkland Islands'
    | 'Faroe Islands'
    | 'Fiji'
    | 'Finland'
    | 'France'
    | 'French Guiana'
    | 'French Polynesia'
    | 'French Southern Territories'
    | 'Gabon'
    | 'Gambia'
    | 'Georgia'
    | 'Germany'
    | 'Ghana'
    | 'Gibraltar'
    | 'Greece'
    | 'Greenland'
    | 'Grenada'
    | 'Guadeloupe'
    | 'Guam'
    | 'Guatemala'
    | 'Guernsey'
    | 'Guinea-Bissau'
    | 'Guinea'
    | 'Guyana'
    | 'Haiti'
    | 'Heard & McDonald Islands'
    | 'Honduras'
    | 'Hong Kong SAR China'
    | 'Hungary'
    | 'Iceland'
    | 'India'
    | 'Indonesia'
    | 'Iran'
    | 'Iraq'
    | 'Ireland'
    | 'Isle of Man'
    | 'Israel'
    | 'Italy'
    | 'Jamaica'
    | 'Japan'
    | 'Jersey'
    | 'Jordan'
    | 'Kazakhstan'
    | 'Kenya'
    | 'Kiribati'
    | 'Kosovo'
    | 'Kuwait'
    | 'Kyrgyzstan'
    | 'Laos'
    | 'Latvia'
    | 'Lebanon'
    | 'Lesotho'
    | 'Liberia'
    | 'Libya'
    | 'Liechtenstein'
    | 'Lithuania'
    | 'Luxembourg'
    | 'Macao SAR China'
    | 'Madagascar'
    | 'Malawi'
    | 'Malaysia'
    | 'Maldives'
    | 'Mali'
    | 'Malta'
    | 'Marshall Islands'
    | 'Martinique'
    | 'Mauritania'
    | 'Mauritius'
    | 'Mayotte'
    | 'Mexico'
    | 'Micronesia'
    | 'Moldova'
    | 'Monaco'
    | 'Mongolia'
    | 'Montenegro'
    | 'Montserrat'
    | 'Morocco'
    | 'Mozambique'
    | 'Myanmar (Burma)'
    | 'Namibia'
    | 'Nauru'
    | 'Nepal'
    | 'Netherlands'
    | 'New Caledonia'
    | 'New Zealand'
    | 'Nicaragua'
    | 'Niger'
    | 'Nigeria'
    | 'Niue'
    | 'Norfolk Island'
    | 'North Korea'
    | 'North Macedonia'
    | 'Northern Mariana Islands'
    | 'Norway'
    | 'Oman'
    | 'Pakistan'
    | 'Palau'
    | 'Palestine'
    | 'Panama'
    | 'Papua New Guinea'
    | 'Paraguay'
    | 'Peru'
    | 'Philippines'
    | 'Pitcairn Islands'
    | 'Poland'
    | 'Portugal'
    | 'Puerto Rico'
    | 'Qatar'
    | 'R\xE9union'
    | 'Romania'
    | 'Russia'
    | 'Rwanda'
    | 'Samoa'
    | 'San Marino'
    | 'S\xE3o Tom\xE9 & Pr\xEDncipe'
    | 'Sark'
    | 'Saudi Arabia'
    | 'Senegal'
    | 'Serbia'
    | 'Seychelles'
    | 'Sierra Leone'
    | 'Singapore'
    | 'Sint Maarten'
    | 'Slovakia'
    | 'Slovenia'
    | 'Solomon Islands'
    | 'Somalia'
    | 'South Africa'
    | 'South Georgia & South Sandwich Islands'
    | 'South Korea'
    | 'South Sudan'
    | 'Spain'
    | 'Sri Lanka'
    | 'St. Barth\xE9lemy'
    | 'St. Helena'
    | 'St. Kitts & Nevis'
    | 'St. Lucia'
    | 'St. Martin'
    | 'St. Pierre & Miquelon'
    | 'St. Vincent & Grenadines'
    | 'Sudan'
    | 'Suriname'
    | 'Svalbard & Jan Mayen'
    | 'Sweden'
    | 'Switzerland'
    | 'Syria'
    | 'Taiwan'
    | 'Tajikistan'
    | 'Tanzania'
    | 'Thailand'
    | 'Timor-Leste'
    | 'Togo'
    | 'Tokelau'
    | 'Tonga'
    | 'Trinidad & Tobago'
    | 'Tristan da Cunha'
    | 'Tunisia'
    | 'T\xFCrkiye'
    | 'Turkmenistan'
    | 'Turks & Caicos Islands'
    | 'Tuvalu'
    | 'U.S. Outlying Islands'
    | 'U.S. Virgin Islands'
    | 'Uganda'
    | 'Ukraine'
    | 'United Arab Emirates'
    | 'United Kingdom'
    | 'Uruguay'
    | 'USA'
    | 'Uzbekistan'
    | 'Vanuatu'
    | 'Vatican City'
    | 'Venezuela'
    | 'Vietnam'
    | 'Wallis & Futuna'
    | 'Western Sahara'
    | 'Yemen'
    | 'Zambia'
    | 'Zimbabwe'
  > | null;
  college:
    | 'CBS'
    | 'CCAPS'
    | 'CDES'
    | 'CEHD'
    | 'CFANS'
    | 'CLA'
    | 'COP'
    | 'CSE'
    | 'CSOM'
    | 'CVM'
    | 'HSPA'
    | 'MED'
    | 'SOD'
    | 'SON'
    | 'SPH'
    | null;
  major: string | null;
  classYear: number | null;
  techStack: Array<
    | 'adobe suite'
    | 'airflow'
    | 'airtable'
    | 'angular'
    | 'ansible'
    | 'anthropic'
    | 'astro'
    | 'aws'
    | 'babel'
    | 'bootstrap'
    | 'bun'
    | 'c'
    | 'c#'
    | 'c++'
    | 'canva'
    | 'clojure'
    | 'cloudflare'
    | 'confluence'
    | 'dart'
    | 'databricks'
    | 'digitalocean'
    | 'django'
    | 'docker'
    | 'elasticsearch'
    | 'electron'
    | 'elixir'
    | 'erlang'
    | 'excel'
    | 'expo'
    | 'express.js'
    | 'express'
    | 'fastapi'
    | 'figma'
    | 'firebase'
    | 'flask'
    | 'flutter'
    | 'framer'
    | 'gatsby'
    | 'gcp'
    | 'git'
    | 'github'
    | 'gitlab'
    | 'go'
    | 'graphql'
    | 'hadoop'
    | 'haskell'
    | 'hasura'
    | 'hugging face'
    | 'java'
    | 'javascript'
    | 'jenkins'
    | 'jest'
    | 'jira'
    | 'jquery'
    | 'jupyter'
    | 'kafka'
    | 'kotlin'
    | 'kubernetes'
    | 'langchain'
    | 'laravel'
    | 'linear'
    | 'linux'
    | 'mariadb'
    | 'material ui'
    | 'mongodb'
    | 'mui'
    | 'mysql'
    | 'neovim'
    | 'nestjs'
    | 'netlify'
    | 'next.js'
    | 'nextjs'
    | 'nginx'
    | 'node.js'
    | 'nodejs'
    | 'notion'
    | 'numpy'
    | 'nuxt.js'
    | 'nuxt'
    | 'nuxtjs'
    | 'openai'
    | 'openjdk'
    | 'oracle'
    | 'pandas'
    | 'perplexity'
    | 'php'
    | 'postgresql'
    | 'postman'
    | 'prisma'
    | 'python'
    | 'pytorch'
    | 'r'
    | 'rabbitmq'
    | 'react router'
    | 'react.js'
    | 'react'
    | 'reactjs'
    | 'redis'
    | 'redux'
    | 'remix'
    | 'rstudio'
    | 'ruby on rails'
    | 'ruby'
    | 'rust'
    | 'sass'
    | 'scala'
    | 'shopify'
    | 'sklearn'
    | 'slack'
    | 'snowflake'
    | 'socket.io'
    | 'spark'
    | 'springboot'
    | 'sql'
    | 'sqlite'
    | 'storybook'
    | 'supabase'
    | 'svelte'
    | 'swift'
    | 'tableau'
    | 'tailwind css'
    | 'tailwind'
    | 'tailwindcss'
    | 'tensorflow'
    | 'terraform'
    | 'three.js'
    | 'trello'
    | 'typescript'
    | 'ubuntu'
    | 'unity'
    | 'unreal engine'
    | 'vercel'
    | 'vim'
    | 'vite'
    | 'vitest'
    | 'vue.js'
    | 'vue'
    | 'vuejs'
    | 'webflow'
    | 'webpack'
    | 'wordpress'
    | 'xcode'
  > | null;
  companies: Array<string> | null;
  highlights: Array<string> | null;
  hobbies: Array<string> | null;
  links: Array<{
    type:
      | 'facebook'
      | 'github'
      | 'instagram'
      | 'linkedin'
      | 'other'
      | 'portfolio'
      | 'twitch'
      | 'x'
      | 'youtube'
      | null;
    label: string | null;
    url: string | null;
  }> | null;
} | null;
// Variable: OFFICER_IDENTIFIERS_QUERY
// Query: *[_type == "officer"]{    id,    "slug": slug.current  }
export type OFFICER_IDENTIFIERS_QUERYResult = Array<{
  id: string | null;
  slug: string | null;
}>;

// Source: sanity/lib/queries/project.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"]    | order(        select(          stage == "dev" => 0,          stage == "release" => 1,          stage == "unsupported" => 2,          3        ) asc,        _createdAt desc      ) {    _id,    id,    title,    description,    tags,    type,    stage,    href,    img,    color,    stats {      users,      rating    }  }
export type PROJECTS_QUERYResult = Array<{
  _id: string;
  id: string | null;
  title: string | null;
  description: string | null;
  tags: Array<string> | null;
  type: 'mobile' | 'web' | null;
  stage: 'dev' | 'release' | 'unsupported' | null;
  href: string | null;
  img: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  } | null;
  color: string | null;
  stats: {
    users: number | null;
    rating: number | null;
  } | null;
}>;
// Variable: PROJECTS_BY_SLUGS_QUERY
// Query: *[    _type == "project" &&    (      id in $slugs ||      slug.current in $slugs    )  ] {    _id,    id,    "slug": coalesce(slug.current, id),    title,    description,    tags,    type,    stage,    href,    img,    color,    stats {      users,      rating    }  }
export type PROJECTS_BY_SLUGS_QUERYResult = Array<{
  _id: string;
  id: string | null;
  slug: string | null;
  title: string | null;
  description: string | null;
  tags: Array<string> | null;
  type: 'mobile' | 'web' | null;
  stage: 'dev' | 'release' | 'unsupported' | null;
  href: string | null;
  img: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  } | null;
  color: string | null;
  stats: {
    users: number | null;
    rating: number | null;
  } | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "event" && date >= now()] | order(date asc) {\n    _id,\n    id,\n    title,\n    description,\n    link,\n    date,\n    location,\n    attendees,\n    type,\n    featured\n  }\n': EVENTS_QUERYResult;
    '\n  *[_type == "officer"] | order(id asc) {\n    \n  _id,\n  id,\n  "slug": slug.current,\n  givenName,\n  familyName,\n  current,\n  specialization,\n  positions[] {\n    position,\n    startYear,\n    endYear\n  },\n  "logo": logo.asset->url,\n  "projects": projects[]->{\n    "identifier": coalesce(slug.current, id)\n  }[].identifier,\n  "modelUrl": modelFile.asset->url,\n  bioShort,\n  bioLong,\n  detailsTitle,\n  leadershipStyle,\n  nationalities,\n  college,\n  major,\n  classYear,\n  techStack,\n  companies,\n  highlights,\n  hobbies,\n  links[] {\n    type,\n    label,\n    url\n  }\n\n  }\n': OFFICERS_QUERYResult;
    '\n  *[\n    _type == "officer" &&\n    (\n      lower(slug.current) == $slugIdentifier ||\n      lower(id) == $hexIdentifier\n    )\n  ][0] {\n    \n  _id,\n  id,\n  "slug": slug.current,\n  givenName,\n  familyName,\n  current,\n  specialization,\n  positions[] {\n    position,\n    startYear,\n    endYear\n  },\n  "logo": logo.asset->url,\n  "projects": projects[]->{\n    "identifier": coalesce(slug.current, id)\n  }[].identifier,\n  "modelUrl": modelFile.asset->url,\n  bioShort,\n  bioLong,\n  detailsTitle,\n  leadershipStyle,\n  nationalities,\n  college,\n  major,\n  classYear,\n  techStack,\n  companies,\n  highlights,\n  hobbies,\n  links[] {\n    type,\n    label,\n    url\n  }\n\n  }\n': OFFICER_BY_IDENTIFIER_QUERYResult;
    '\n  *[_type == "officer"]{\n    id,\n    "slug": slug.current\n  }\n': OFFICER_IDENTIFIERS_QUERYResult;
    '\n  *[_type == "project"]\n    | order(\n        select(\n          stage == "dev" => 0,\n          stage == "release" => 1,\n          stage == "unsupported" => 2,\n          3\n        ) asc,\n        _createdAt desc\n      ) {\n    _id,\n    id,\n    title,\n    description,\n    tags,\n    type,\n    stage,\n    href,\n    img,\n    color,\n    stats {\n      users,\n      rating\n    }\n  }\n': PROJECTS_QUERYResult;
    '\n  *[\n    _type == "project" &&\n    (\n      id in $slugs ||\n      slug.current in $slugs\n    )\n  ] {\n    _id,\n    id,\n    "slug": coalesce(slug.current, id),\n    title,\n    description,\n    tags,\n    type,\n    stage,\n    href,\n    img,\n    color,\n    stats {\n      users,\n      rating\n    }\n  }\n': PROJECTS_BY_SLUGS_QUERYResult;
  }
}
