import { BriefcaseBusiness, Database } from 'lucide-react';
import {
  FaAmazon,
  FaApple,
  FaGoogle,
  FaJava,
  FaMeta,
  FaMicrosoft,
  FaTiktok,
} from 'react-icons/fa6';
import {
  SiAdobe,
  SiAirbnb,
  SiAirtable,
  SiAmd,
  SiAngular,
  SiAnsible,
  SiAnthropic,
  SiAmazonwebservices,
  SiApacheairflow,
  SiApachehadoop,
  SiApachekafka,
  SiApachespark,
  SiArm,
  SiAstro,
  SiAtlassian,
  SiBabel,
  SiBaidu,
  SiBootstrap,
  SiBroadcom,
  SiBun,
  SiBytedance,
  SiC,
  SiCanva,
  SiCisco,
  SiCloudflare,
  SiClojure,
  SiCoinbase,
  SiConfluence,
  SiCplusplus,
  SiDart,
  SiDatabricks,
  SiDatadog,
  SiDell,
  SiDigitalocean,
  SiDjango,
  SiDocker,
  SiDotnet,
  SiDropbox,
  SiEbay,
  SiElasticsearch,
  SiElectron,
  SiElixir,
  SiEpicgames,
  SiErlang,
  SiExpo,
  SiExpress,
  SiFastapi,
  SiFirebase,
  SiFigma,
  SiFlask,
  SiFlutter,
  SiFramer,
  SiGatsby,
  SiGit,
  SiGithub,
  SiGitlab,
  SiGo,
  SiGooglecloud,
  SiGraphql,
  SiHasura,
  SiHaskell,
  SiHp,
  SiHuawei,
  SiHuggingface,
  SiIntel,
  SiJenkins,
  SiJest,
  SiJira,
  SiJquery,
  SiJupyter,
  SiKotlin,
  SiKubernetes,
  SiLangchain,
  SiLaravel,
  SiLenovo,
  SiLinear,
  SiLinkedin,
  SiLinux,
  SiLyft,
  SiMariadb,
  SiMaterialdesign,
  SiMui,
  SiMysql,
  SiNestjs,
  SiNetlify,
  SiNeovim,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiNotion,
  SiNumpy,
  SiNuxtdotjs,
  SiNvidia,
  SiOpenai,
  SiOpenjdk,
  SiOracle,
  SiPandas,
  SiPalantir,
  SiPaypal,
  SiPerplexity,
  SiPhp,
  SiPinterest,
  SiPostgresql,
  SiPostman,
  SiPrisma,
  SiPython,
  SiPytorch,
  SiR,
  SiRabbitmq,
  SiReact,
  SiReactrouter,
  SiRedis,
  SiRedux,
  SiRemix,
  SiRiotgames,
  SiRobinhood,
  SiRstudioide,
  SiRuby,
  SiRubyonrails,
  SiSalesforce,
  SiSamsung,
  SiSass,
  SiScala,
  SiScikitlearn,
  SiShopify,
  SiSlack,
  SiSnapchat,
  SiSnowflake,
  SiSocketdotio,
  SiSony,
  SiSpotify,
  SiSplunk,
  SiSqlite,
  SiStripe,
  SiStorybook,
  SiSupabase,
  SiSvelte,
  SiSwift,
  SiTableau,
  SiTailwindcss,
  SiTensorflow,
  SiTerraform,
  SiTesla,
  SiThreedotjs,
  SiTrello,
  SiTwilio,
  SiTypescript,
  SiUber,
  SiUbuntu,
  SiUnity,
  SiUnrealengine,
  SiVercel,
  SiVim,
  SiVite,
  SiVitest,
  SiVmware,
  SiVuedotjs,
  SiWebflow,
  SiWebpack,
  SiWordpress,
  SiXcode,
  SiXiaomi,
  SiYcombinator,
  SiZoom,
  SiReddit,
  SiNetflix,
  SiQualcomm,
  SiRust,
  SiSpringboot,
  SiMongodb,
  SiJavascript,
} from 'react-icons/si';
import type { IconComponent, TechMapItem } from './types';

export const techMap: Record<string, TechMapItem> = {
  c: {
    icon: SiC,
    url: 'https://en.wikipedia.org/wiki/C_(programming_language)',
  },
  'c++': {
    icon: SiCplusplus,
    url: 'https://isocpp.org/',
  },
  'c#': {
    icon: SiDotnet,
    url: 'https://dotnet.microsoft.com/languages/csharp',
  },
  typescript: {
    icon: SiTypescript,
    url: 'https://www.typescriptlang.org/',
  },
  javascript: {
    icon: SiJavascript,
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  },
  java: {
    icon: FaJava,
    url: 'https://www.java.com/',
  },
  openjdk: {
    icon: SiOpenjdk,
    url: 'https://openjdk.org/',
  },
  python: {
    icon: SiPython,
    url: 'https://www.python.org/',
  },
  php: {
    icon: SiPhp,
    url: 'https://www.php.net/',
  },
  ruby: {
    icon: SiRuby,
    url: 'https://www.ruby-lang.org/',
  },
  rust: {
    icon: SiRust,
    url: 'https://rust-lang.org/',
  },
  go: {
    icon: SiGo,
    url: 'https://go.dev/',
  },
  kotlin: {
    icon: SiKotlin,
    url: 'https://kotlinlang.org/',
  },
  swift: {
    icon: SiSwift,
    url: 'https://www.swift.org/',
  },
  dart: {
    icon: SiDart,
    url: 'https://dart.dev/',
  },
  scala: {
    icon: SiScala,
    url: 'https://www.scala-lang.org/',
  },
  haskell: {
    icon: SiHaskell,
    url: 'https://www.haskell.org/',
  },
  elixir: {
    icon: SiElixir,
    url: 'https://elixir-lang.org/',
  },
  erlang: {
    icon: SiErlang,
    url: 'https://www.erlang.org/',
  },
  clojure: {
    icon: SiClojure,
    url: 'https://clojure.org/',
  },
  r: {
    icon: SiR,
    url: 'https://www.r-project.org/',
  },
  react: {
    icon: SiReact,
    url: 'https://react.dev/',
  },
  'react native': {
    icon: SiReact,
    url: 'https://reactnative.dev/',
  },
  'react.js': {
    icon: SiReact,
    url: 'https://react.dev/',
  },
  reactjs: {
    icon: SiReact,
    url: 'https://react.dev/',
  },
  'next.js': {
    icon: SiNextdotjs,
    url: 'https://nextjs.org/',
  },
  nextjs: {
    icon: SiNextdotjs,
    url: 'https://nextjs.org/',
  },
  'vue.js': {
    icon: SiVuedotjs,
    url: 'https://vuejs.org/',
  },
  vue: {
    icon: SiVuedotjs,
    url: 'https://vuejs.org/',
  },
  vuejs: {
    icon: SiVuedotjs,
    url: 'https://vuejs.org/',
  },
  'nuxt.js': {
    icon: SiNuxtdotjs,
    url: 'https://nuxt.com/',
  },
  nuxt: {
    icon: SiNuxtdotjs,
    url: 'https://nuxt.com/',
  },
  nuxtjs: {
    icon: SiNuxtdotjs,
    url: 'https://nuxt.com/',
  },
  angular: {
    icon: SiAngular,
    url: 'https://angular.dev/',
  },
  svelte: {
    icon: SiSvelte,
    url: 'https://svelte.dev/',
  },
  remix: {
    icon: SiRemix,
    url: 'https://remix.run/',
  },
  astro: {
    icon: SiAstro,
    url: 'https://astro.build/',
  },
  gatsby: {
    icon: SiGatsby,
    url: 'https://www.gatsbyjs.com/',
  },
  nestjs: {
    icon: SiNestjs,
    url: 'https://nestjs.com/',
  },
  springboot: {
    icon: SiSpringboot,
    url: 'https://spring.io/projects/spring-boot',
  },
  'node.js': {
    icon: SiNodedotjs,
    url: 'https://nodejs.org/',
  },
  nodejs: {
    icon: SiNodedotjs,
    url: 'https://nodejs.org/',
  },
  'express.js': {
    icon: SiExpress,
    url: 'https://expressjs.com/',
  },
  express: {
    icon: SiExpress,
    url: 'https://expressjs.com/',
  },
  fastapi: {
    icon: SiFastapi,
    url: 'https://fastapi.tiangolo.com/',
  },
  django: {
    icon: SiDjango,
    url: 'https://www.djangoproject.com/',
  },
  flask: {
    icon: SiFlask,
    url: 'https://flask.palletsprojects.com/',
  },
  laravel: {
    icon: SiLaravel,
    url: 'https://laravel.com/',
  },
  'ruby on rails': {
    icon: SiRubyonrails,
    url: 'https://rubyonrails.org/',
  },
  graphql: {
    icon: SiGraphql,
    url: 'https://graphql.org/',
  },
  hasura: {
    icon: SiHasura,
    url: 'https://hasura.io/',
  },
  'socket.io': {
    icon: SiSocketdotio,
    url: 'https://socket.io/',
  },
  redux: {
    icon: SiRedux,
    url: 'https://redux.js.org/',
  },
  'react router': {
    icon: SiReactrouter,
    url: 'https://reactrouter.com/',
  },
  vite: {
    icon: SiVite,
    url: 'https://vite.dev/',
  },
  webpack: {
    icon: SiWebpack,
    url: 'https://webpack.js.org/',
  },
  babel: {
    icon: SiBabel,
    url: 'https://babeljs.io/',
  },
  jest: {
    icon: SiJest,
    url: 'https://jestjs.io/',
  },
  vitest: {
    icon: SiVitest,
    url: 'https://vitest.dev/',
  },
  storybook: {
    icon: SiStorybook,
    url: 'https://storybook.js.org/',
  },
  jquery: {
    icon: SiJquery,
    url: 'https://jquery.com/',
  },
  bootstrap: {
    icon: SiBootstrap,
    url: 'https://getbootstrap.com/',
  },
  sass: {
    icon: SiSass,
    url: 'https://sass-lang.com/',
  },
  'material ui': {
    icon: SiMui,
    url: 'https://mui.com/',
  },
  mui: {
    icon: SiMui,
    url: 'https://mui.com/',
  },
  'three.js': {
    icon: SiThreedotjs,
    url: 'https://threejs.org/',
  },
  framer: {
    icon: SiFramer,
    url: 'https://www.framer.com/motion/',
  },
  expo: {
    icon: SiExpo,
    url: 'https://expo.com',
  },
  flutter: {
    icon: SiFlutter,
    url: 'https://flutter.dev/',
  },
  unity: {
    icon: SiUnity,
    url: 'https://unity.com/',
  },
  'unreal engine': {
    icon: SiUnrealengine,
    url: 'https://www.unrealengine.com/',
  },
  xcode: {
    icon: SiXcode,
    url: 'https://developer.apple.com/xcode/',
  },
  mongodb: {
    icon: SiMongodb,
    url: 'https://www.mongodb.com/',
  },
  postgresql: {
    icon: SiPostgresql,
    url: 'https://www.postgresql.org/',
  },
  mysql: {
    icon: SiMysql,
    url: 'https://www.mysql.com/',
  },
  mariadb: {
    icon: SiMariadb,
    url: 'https://mariadb.org/',
  },
  sqlite: {
    icon: SiSqlite,
    url: 'https://sqlite.org/',
  },
  redis: {
    icon: SiRedis,
    url: 'https://redis.io/',
  },
  oracle: {
    icon: SiOracle,
    url: 'https://www.oracle.com/database/',
  },
  elasticsearch: {
    icon: SiElasticsearch,
    url: 'https://www.elastic.co/elasticsearch',
  },
  kafka: {
    icon: SiApachekafka,
    url: 'https://kafka.apache.org/',
  },
  rabbitmq: {
    icon: SiRabbitmq,
    url: 'https://www.rabbitmq.com/',
  },
  docker: {
    icon: SiDocker,
    url: 'https://www.docker.com/',
  },
  kubernetes: {
    icon: SiKubernetes,
    url: 'https://kubernetes.io/',
  },
  terraform: {
    icon: SiTerraform,
    url: 'https://www.terraform.io/',
  },
  ansible: {
    icon: SiAnsible,
    url: 'https://www.ansible.com/',
  },
  nginx: {
    icon: SiNginx,
    url: 'https://nginx.org/',
  },
  linux: {
    icon: SiLinux,
    url: 'https://kernel.org/',
  },
  ubuntu: {
    icon: SiUbuntu,
    url: 'https://ubuntu.com/',
  },
  git: {
    icon: SiGit,
    url: 'https://git-scm.com/',
  },
  github: {
    icon: SiGithub,
    url: 'https://github.com/',
  },
  gitlab: {
    icon: SiGitlab,
    url: 'https://gitlab.com/',
  },
  jenkins: {
    icon: SiJenkins,
    url: 'https://www.jenkins.io/',
  },
  postman: {
    icon: SiPostman,
    url: 'https://www.postman.com/',
  },
  aws: {
    icon: SiAmazonwebservices,
    url: 'https://aws.amazon.com/',
  },
  gcp: {
    icon: SiGooglecloud,
    url: 'https://cloud.google.com/',
  },
  cloudflare: {
    icon: SiCloudflare,
    url: 'https://www.cloudflare.com/',
  },
  digitalocean: {
    icon: SiDigitalocean,
    url: 'https://www.digitalocean.com/',
  },
  firebase: {
    icon: SiFirebase,
    url: 'https://firebase.google.com/',
  },
  netlify: {
    icon: SiNetlify,
    url: 'https://www.netlify.com/',
  },
  vercel: {
    icon: SiVercel,
    url: 'https://vercel.com/',
  },
  supabase: {
    icon: SiSupabase,
    url: 'https://supabase.com/',
  },
  prisma: {
    icon: SiPrisma,
    url: 'https://www.prisma.io/',
  },
  openai: {
    icon: SiOpenai,
    url: 'https://openai.com/',
  },
  anthropic: {
    icon: SiAnthropic,
    url: 'https://www.anthropic.com/',
  },
  perplexity: {
    icon: SiPerplexity,
    url: 'https://www.perplexity.ai/',
  },
  'hugging face': {
    icon: SiHuggingface,
    url: 'https://huggingface.co/',
  },
  langchain: {
    icon: SiLangchain,
    url: 'https://www.langchain.com/',
  },
  tensorflow: {
    icon: SiTensorflow,
    url: 'https://www.tensorflow.org/',
  },
  pytorch: {
    icon: SiPytorch,
    url: 'https://pytorch.org/',
  },
  sklearn: {
    icon: SiScikitlearn,
    url: 'https://scikit-learn.org/',
  },
  pandas: {
    icon: SiPandas,
    url: 'https://pandas.pydata.org/',
  },
  numpy: {
    icon: SiNumpy,
    url: 'https://numpy.org/',
  },
  jupyter: {
    icon: SiJupyter,
    url: 'https://jupyter.org/',
  },
  airflow: {
    icon: SiApacheairflow,
    url: 'https://airflow.apache.org/',
  },
  spark: {
    icon: SiApachespark,
    url: 'https://spark.apache.org/',
  },
  hadoop: {
    icon: SiApachehadoop,
    url: 'https://hadoop.apache.org/',
  },
  databricks: {
    icon: SiDatabricks,
    url: 'https://www.databricks.com/',
  },
  snowflake: {
    icon: SiSnowflake,
    url: 'https://www.snowflake.com/',
  },
  excel: {
    icon: Database,
    url: 'https://www.microsoft.com/microsoft-365/excel',
  },
  sql: {
    icon: Database,
    url: 'https://en.wikipedia.org/wiki/SQL',
  },
  rstudio: {
    icon: SiRstudioide,
    url: 'https://posit.co/products/open-source/rstudio/',
  },
  tableau: {
    icon: SiTableau,
    url: 'https://www.tableau.com/',
  },
  figma: {
    icon: SiFigma,
    url: 'https://www.figma.com/',
  },
  'adobe suite': {
    icon: SiAdobe,
    url: 'https://www.adobe.com/creativecloud.html',
  },
  notion: {
    icon: SiNotion,
    url: 'https://www.notion.so/',
  },
  jira: {
    icon: SiJira,
    url: 'https://www.atlassian.com/software/jira',
  },
  confluence: {
    icon: SiConfluence,
    url: 'https://www.atlassian.com/software/confluence',
  },
  slack: {
    icon: SiSlack,
    url: 'https://slack.com/',
  },
  linear: {
    icon: SiLinear,
    url: 'https://linear.app/',
  },
  airtable: {
    icon: SiAirtable,
    url: 'https://www.airtable.com/',
  },
  trello: {
    icon: SiTrello,
    url: 'https://trello.com/',
  },
  canva: {
    icon: SiCanva,
    url: 'https://www.canva.com/',
  },
  webflow: {
    icon: SiWebflow,
    url: 'https://webflow.com/',
  },
  shopify: {
    icon: SiShopify,
    url: 'https://www.shopify.com/',
  },
  wordpress: {
    icon: SiWordpress,
    url: 'https://wordpress.org/',
  },
  'tailwind css': {
    icon: SiTailwindcss,
    url: 'https://tailwindcss.com/',
  },
  tailwindcss: {
    icon: SiTailwindcss,
    url: 'https://tailwindcss.com/',
  },
  tailwind: {
    icon: SiTailwindcss,
    url: 'https://tailwindcss.com/',
  },
  vim: {
    icon: SiVim,
    url: 'https://www.vim.org/',
  },
  neovim: {
    icon: SiNeovim,
    url: 'https://neovim.io/',
  },
  bun: {
    icon: SiBun,
    url: 'https://bun.sh/',
  },
  electron: {
    icon: SiElectron,
    url: 'https://www.electronjs.org/',
  },
};

export const companyIconMap: Record<string, IconComponent> = {
  amazon: FaAmazon,
  amd: SiAmd,
  adobe: SiAdobe,
  airbnb: SiAirbnb,
  anthropic: SiAnthropic,
  arm: SiArm,
  atlassian: SiAtlassian,
  baidu: SiBaidu,
  broadcom: SiBroadcom,
  bytedance: SiBytedance,
  canva: SiCanva,
  cisco: SiCisco,
  cloudflare: SiCloudflare,
  coinbase: SiCoinbase,
  databricks: SiDatabricks,
  datadog: SiDatadog,
  dell: SiDell,
  digitalocean: SiDigitalocean,
  dropbox: SiDropbox,
  ebay: SiEbay,
  epicgames: SiEpicgames,
  figma: SiFigma,
  github: SiGithub,
  gitlab: SiGitlab,
  hp: SiHp,
  huawei: SiHuawei,
  ibm: BriefcaseBusiness,
  intel: SiIntel,
  lenovo: SiLenovo,
  linkedin: SiLinkedin,
  lyft: SiLyft,
  microsoft: FaMicrosoft,
  netlify: SiNetlify,
  nvidia: SiNvidia,
  openai: SiOpenai,
  oracle: SiOracle,
  palantir: SiPalantir,
  paypal: SiPaypal,
  perplexity: SiPerplexity,
  pinterest: SiPinterest,
  reddit: SiReddit,
  riotgames: SiRiotgames,
  robinhood: SiRobinhood,
  salesforce: SiSalesforce,
  samsung: SiSamsung,
  shopify: SiShopify,
  slack: SiSlack,
  snapchat: SiSnapchat,
  snowflake: SiSnowflake,
  sony: SiSony,
  spotify: SiSpotify,
  splunk: SiSplunk,
  tiktok: FaTiktok,
  twilio: SiTwilio,
  uber: SiUber,
  vmware: SiVmware,
  webflow: SiWebflow,
  xiaomi: SiXiaomi,
  ycombinator: SiYcombinator,
  zoom: SiZoom,
  apple: FaApple,
  meta: FaMeta,
  google: FaGoogle,
  netflix: SiNetflix,
  tesla: SiTesla,
  qualcomm: SiQualcomm,
  stripe: SiStripe,
};

export const companyFallbackIcon = BriefcaseBusiness;
